### ISSUE TITLE
Application crashes when signing in

### ISSUE THREAD

**Issue by leafpool243** [vector-im/element-x-android#1030]
### Steps to reproduce

1. Open app
2. Log in (homeserver: matrix.org)

#### What did you expect?
I should be logged in.

#### What happened instead?
App crashes. Further attempts to open the app continue to crash.

![Screenshot_20230806-194113](https://github.com/vector-im/element-x-android/assets/63614345/1447f881-7697-4c25-bd59-147abe698ed7)

### Your phone model

SM-G532G [Samsung Galaxy J2 Prime]

### Operating system version

6.0.1

### Application version and app store

Latest nightly build from Firebase app distribution from 4 Aug ’23

### Homeserver

matrix.org

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by leafpool243** [comment]
Can’t send logs as I can’t even open the app.

**Comment by jmartinesp** [comment]
Without logs it's really difficult to debug this. If you upgrade to a newer version of the nightly, does this keep happening? We had some issues with a version of the Rust SDK and asynchronous code that could crash the app while doing certain tasks, and that should be fixed now, so maybe this issue is fixed too.

**Comment by leafpool243** [comment]
@jmartinesp Unfortunately, it still crashes. Nightly build from today/yesterday, 11–12 August.

Are logs stored anywhere on the device? Maybe I could upload them manually.

**Comment by jmartinesp** [comment]
We tried to reproduce this on our side with a device using the same OS version but we couldn't, sorry. It works fine for us.

As for the logs: they're on the internal cache directory of the app, so unless you have a rooted phone you won't be able to access them. 

I also tried checking if anything had been uploaded to Sentry, but as it crashed before you got to select whether to enable analytics or not, nothing was uploaded automatically.

You could probably still get some real time logs using [ADB logcat](https://developer.android.com/tools/logcat). Is that something you could do?

**Comment by leafpool243** [comment]
[element-nightly-logs.txt](https://github.com/vector-im/element-x-android/files/12365694/element-nightly-logs.txt)

Starts right before I open the app and ends a few seconds after it has crashed.

**Comment by leafpool243** [comment]
Interesting!

**Comment by bmarty** [comment]
We have upgraded the Google crypto library (in [this PR](https://github.com/vector-im/element-x-android/pull/1101)), it may fix this issue. @leafpool243 can you install the latest nightly and report the result here please?

**Comment by andybalaam** [comment]
Similar problem here on a Samsung Galaxy A13 with Android 13 build number TP1A.220624.014.A135FXXS5CWG1.

The app freezes after login, dropping back to the Android home screen, with no crash pop-up at all.

**Comment by leafpool243** [comment]
@bmarty It works now!! Thank you

**Comment by jmartinesp** [comment]
> Similar problem here on a Samsung Galaxy A13 with Android 13 build number TP1A.220624.014.A135FXXS5CWG1.
> 
> Element X version 0.1.2 (16 Aug 2023).
> 
> The app freezes after login, dropping back to the Android home screen, with no crash pop-up at all.
> 
> (This is the latest beta build. Not able to access the nightly on this device.)

Thanks @andybalaam . Could you create another issue and provide some logs? I guess no rageshakes would be uploaded at that point, but maybe you have access to logcat?

**Comment by jmartinesp** [comment]
Closing this issue as the original problem seems to be fixed.

**Comment by andybalaam** [comment]
> Thanks @andybalaam . Could you create another issue and provide some logs? I guess no rageshakes would be uploaded at that point, but maybe you have access to logcat?

Thanks, if I get a chance (it's not my device) I will try to get some logs from logcat and log a new issue.
